### ISSUE TITLE
login fails on linux 

### ISSUE THREAD

**Issue by sherifmayika** [OSL-Works/Steam-Auto-Friend#2]
here is my CMD result after running the code 
:~/Desktop/facebook tools/Steam-Auto-Friend-master$ node index.js
8888888b.          .d888888                              
888   Y88b        d88P" 888                              
888    888        888   888                              
888   d88P .d88b. 888888888 .d88b.  .d88b. 888  888  888
8888888P" d8P  Y8b888   888d88""88bd88""88b888  888  888
888 T88b  88888888888   888888  888888  888888  888  888
888  T88b Y8b.    888   888Y88..88PY88..88PY88b 888 d88P 
888   T88b "Y8888 888   888 "Y88P"  "Y88P"  "Y8888888P" 

This bot was developed by MajokingGames
Verision 1.3.0 Free to use
Thanks for choosing us.
This version doesnt contain UI. Login not required...
Loading config file...
Starting bot...
If bot doesnt start in next 1 minute steam is down.

| [GitHub] | VERSION |: You're running the latest version of steam-auto-friend (v1.3.0)

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/logon.js:363:16)
    at SteamUser._handleMessage (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:198:13)
    at CMClient._netMsgReceived (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:198:13)
    at TCPConnection._readPacket (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/tcp_connection.js:183:7)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
Emitted 'error' event at:
    at SteamUser._handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/logon.js:366:9)
    at SteamUser._handleMessage (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/messages.js:249:30)
    [... lines matching original stack trace ...]
    at emitReadable_ (_stream_readable.js:555:12)
aladin@toshiba-satalite:~/Desktop/facebook tools/Steam-Auto-Friend-master$ node index.js
8888888b.          .d888888                              
888   Y88b        d88P" 888                              
888    888        888   888                              
888   d88P .d88b. 888888888 .d88b.  .d88b. 888  888  888
8888888P" d8P  Y8b888   888d88""88bd88""88b888  888  888
888 T88b  88888888888   888888  888888  888888  888  888
888  T88b Y8b.    888   888Y88..88PY88..88PY88b 888 d88P 
888   T88b "Y8888 888   888 "Y88P"  "Y88P"  "Y8888888P" 

This bot was developed by MajokingGames
Verision 1.3.0 Free to use
Thanks for choosing us.
This version doesnt contain UI. Login not required...
Loading config file...
Starting bot...
If bot doesnt start in next 1 minute steam is down.

| [GitHub] | VERSION |: You're running the latest version of steam-auto-friend (v1.3.0)

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/logon.js:363:16)
    at SteamUser._handleMessage (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:198:13)
    at CMClient._netMsgReceived (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:198:13)
    at TCPConnection._readPacket (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-client/lib/tcp_connection.js:183:7)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
Emitted 'error' event at:
    at SteamUser._handlers.(anonymous function) (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/logon.js:366:9)
    at SteamUser._handleMessage (/home/aladin/Desktop/facebook tools/Steam-Auto-Friend-master/node_modules/steam-user/components/messages.js:249:30)
    [... lines matching original stack trace ...]
    at emitReadable_ (_stream_readable.js:555:12)

**Comment by Refloow** [comment]
Error: InvalidPassword
That error indicates that password of the provided steam account is incorrect or if credentials are right it can indicate too many wrong attempts.
Try double checking the credentials so there is no extra spaces or caps letters where there is not supposed to be any since passwords tend to be case sensitive...
If you have any more issues you can join our support discord server, or if you want to support the project leave an star on the repository.
